# Generated by Django 4.0.2 on 2022-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfirstname', models.CharField(max_length=30)),
                ('mylastname', models.CharField(max_length=30)),
                ('mydistrict', models.CharField(max_length=30)),
                ('myphone', models.CharField(max_length=10)),
                ('mytype', models.CharField(max_length=30)),
                ('myage', models.CharField(max_length=2)),
            ],
        ),
    ]
