# Generated by Django 4.0.2 on 2022-02-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
