# Generated by Django 4.0.2 on 2022-02-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donor_eligible_donor_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
