# Generated by Django 4.0.2 on 2022-02-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_donor_eligible_alter_donor_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
