# Generated by Django 4.0.2 on 2022-02-24 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_donor_eligible_alter_donor_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
