# Generated by Django 4.0.2 on 2022-02-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_description_notice_descripton_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
