# Generated by Django 4.0.2 on 2022-02-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
