# Generated by Django 4.0.2 on 2022-02-24 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_notice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
