# Generated by Django 4.0.2 on 2022-02-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_notice_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='listofbanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.URLField(max_length=400)),
            ],
        ),
    ]
