# Generated by Django 4.0.2 on 2022-02-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_listofbanks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listofbanks',
            new_name='listofbank',
        ),
    ]
