# Generated by Django 4.0.2 on 2022-02-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_listofbank_locationame_alter_listofbank_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofbank',
            name='htmlfile',
            field=models.URLField(default='none', max_length=10),
        ),
    ]
