# Generated by Django 4.0.2 on 2022-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_listofbank_htmlfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofbank',
            name='htmlfile',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
