# Generated by Django 4.0.2 on 2022-02-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_listofbank_htmlfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofbank',
            name='htmlfile',
        ),
    ]
