# Generated by Django 4.0.2 on 2022-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_bhaktapurbloodbank_remove_listofbank_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhaktapurbloodbank',
            old_name='name',
            new_name='bankname',
        ),
        migrations.RenameField(
            model_name='bhaktapurbloodbank',
            old_name='phone',
            new_name='bankphone',
        ),
        migrations.AddField(
            model_name='bhaktapurbloodbank',
            name='ABminus',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='bhaktapurbloodbank',
            name='ABplus',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='bhaktapurbloodbank',
            name='Aminus',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='bhaktapurbloodbank',
            name='Bminus',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='bhaktapurbloodbank',
            name='Bplus',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='bhaktapurbloodbank',
            name='Ominus',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='bhaktapurbloodbank',
            name='Oplus',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Aplus',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='locationame',
            field=models.CharField(max_length=100),
        ),
    ]
