# Generated by Django 4.0.2 on 2022-02-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_name_bhaktapurbloodbank_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='ABminus',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='ABplus',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Aminus',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Aplus',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Bminus',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Bplus',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Oplus',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
