# Generated by Django 4.0.2 on 2022-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_bhaktapurbloodbank_delete_listofbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='listofbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=300)),
                ('bankphone', models.CharField(max_length=10)),
                ('locationname', models.CharField(max_length=100)),
                ('location', models.URLField()),
            ],
        ),
    ]
