# Generated by Django 4.0.2 on 2022-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_bhaktapurbloodbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofbank',
            name='htmlfile',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
