# Generated by Django 4.0.2 on 2022-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_listofbank_htmlfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhaktapurbloodbank',
            name='bankid',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='ABminus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='ABplus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Aminus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Aplus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Bminus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Bplus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Ominus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bhaktapurbloodbank',
            name='Oplus',
            field=models.CharField(max_length=30),
        ),
    ]
