# Generated by Django 4.0.2 on 2022-03-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_cbtc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cbtc',
            new_name='cbtcbb',
        ),
    ]
