# Generated by Django 4.0.2 on 2022-03-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_tuhbb'),
    ]

    operations = [
        migrations.CreateModel(
            name='mwhbb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankid', models.CharField(default='4', max_length=100)),
                ('Aplus', models.CharField(max_length=30)),
                ('Aminus', models.CharField(max_length=30)),
                ('Bplus', models.CharField(max_length=30)),
                ('Bminus', models.CharField(max_length=30)),
                ('ABplus', models.CharField(max_length=30)),
                ('ABminus', models.CharField(max_length=30)),
                ('Oplus', models.CharField(max_length=30)),
                ('Ominus', models.CharField(max_length=30)),
            ],
        ),
    ]
